// Problem : Spot The Difference

/****************************************************************************************************************************************************************************************************************************************************************************************************************
 * This question is asked by Google. You are given two strings, s and t which only consist of lowercase letters. t is generated by shuffling the letters in s as well as potentially adding an additional random character. Return the letter that was randomly added to t if it exists, otherwise, return � �. *
 * Note: You may assume that at most one additional character can be added to t.                                                                                                                                                                                                                                *
 *                                                                                                                                                                                                                                                                                                              *
 * Ex: Given the following strings...                                                                                                                                                                                                                                                                           *
 *                                                                                                                                                                                                                                                                                                              *
 * s = "foobar", t = "barfoot", return 't'                                                                                                                                                                                                                                                                      *
 * s = "ide", t = "idea", return 'a'                                                                                                                                                                                                                                                                            *
 * s = "coding", t "ingcod", return ''                                                                                                                                                                                                                                                                          *
 ***************************************************************************************************************************************************************************************************************************************************************************************************************/

class Solution {
	
	static char spotTheDifference(String s, String t) {
		int[] arr1 = new int[26], arr2 = new int[26];
		
		for (int i = 0; i < s.length(); ++i) {
			arr1[s.charAt(i) - 97]++;
		}
		
		for (int i = 0; i < t.length(); ++i) {
			arr2[t.charAt(i) - 97]++;
		}
		
		for (int i = 0; i < arr1.length; i++) {
			if(arr1[i] < arr2[i])
				return (char)(i + 97);
		}
		
		return ' ';
	}
	
}